### ISSUE TITLE
ability to filter choices by language of work/edition

### ISSUE THREAD

**Issue by balmas** [PerseusDL/Capitains-Sparrow#20]
From @nevenjovanovic Nitpicking: even when I have "Latin" selected in the Language rubric, I
get results for Greek from "retrieve texts". I guess the form cannot know
what is selected in "retrieve" -- or could it? Anyway, somehow the users
should be informed that they have to correct the Language after they have
chosen a text from "retrieve".

**Comment by PonteIneptique** [comment]
This one is tricky, because it means the plugin would have to depend on something external. The proposed workaround is to make the query tokenizer a parameter while setting it up, being then able to put "lang:lat" behind the scene.
Fixed in @af2499e
