### ISSUE TITLE
add ability to set data in ctsXSLT service to be retrieved in callback

### ISSUE THREAD

**Issue by balmas** [PerseusDL/Capitains-Sparrow#67]
I would like to be able to set data in ctsXSLT service to be retrieved in callback
e.g.

`$(".myelem").ctsXSLT("myservice",{ 

   "driverdata": { "mydata": "foo"},
   "callback": function(data) {
       // do something with driverdata.mydata
   }
});`

**Comment by PonteIneptique** [comment]
I don't understand.
Can you elaborate ?

**Comment by PonteIneptique** [comment]
Rewriten in #69
